### ISSUE TITLE
加载部分图片出现闪退

### ISSUE THREAD

**Issue by yxiangTang** [panpf/zoomimage#32]
E  #++++++++++++++++++++++++++++++++++++++++++#
10:41:51.870 eup                      E  sys default last handle start!
10:41:51.870 AndroidRuntime           E  FATAL EXCEPTION: main
                                         Process: com.trim.app, PID: 6882
                                         java.util.NoSuchElementException: List is empty.
                                                 at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:418)
                                                 at com.github.panpf.zoomimage.view.subsampling.SubsamplingEngine.resetTileManager(SubsamplingEngine.kt:504)
                                                 at com.github.panpf.zoomimage.view.subsampling.SubsamplingEngine.access$resetTileManager(SubsamplingEngine.kt:65)
                                                 at com.github.panpf.zoomimage.view.subsampling.SubsamplingEngine$resetTileDecoder$2.invokeSuspend(SubsamplingEngine.kt:439)
                                                 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                 at android.os.Handler.handleCallback(Handler.java:942)
                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                 at android.os.Looper.loopOnce(Looper.java:201)
                                                 at android.os.Looper.loop(Looper.java:288)
                                                 at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@18e955b, Dispatchers.Main]

![image](https://github.com/user-attachments/assets/608c54c2-bffa-416e-8d40-f402bce948c8)
这里entry.value为空list

使用的是GlideZoomImageView

正在想办法把图导出来

**Comment by panpf** [comment]
由于你这个问题比较难查，所以请提供一个完整的能复现问题的示例项目源码，还得说明运行环境（最好是模拟器）

**Comment by yxiangTang** [comment]
> 由于你这个问题比较难查，所以请提供一个完整的能复现问题的示例项目源码，还得说明运行环境（最好是模拟器）

![不同尺寸2](https://github.com/user-attachments/assets/e1622886-8cbd-48ec-883b-6e3a68052679)
使用用zoomimage Demo，用GlideZoomImageView本地加载该图片即可复现。

**Comment by panpf** [comment]
图片呢？

**Comment by yxiangTang** [comment]
> 图片呢？
[问题图片.zip](https://github.com/user-attachments/files/16360681/default.zip)
这个压缩包解压就是出问题的图片

**Comment by yxiangTang** [comment]
> 图片呢？

大佬你好，请问这个闪退问题有修复版本了吗~

**Comment by panpf** [comment]
已修复，今天发布一个版本出来

**Comment by panpf** [comment]
1.1.0-alpha04 版本已修复此问题并发布

**Comment by yxiangTang** [comment]
> 1.1.0-alpha04 版本已修复此问题并发布

OK，感谢大佬
