### ISSUE TITLE
Subsampling doesn't work for CoilAsyncZoomImage - RuntimeException: Canvas: trying to draw too large(308544000bytes) bitmap.

### ISSUE THREAD

**Issue by szczepanski-k** [panpf/zoomimage#40]
**Describe the bug**

The image size is 12000 × 6428 px
Image format - webp, jpg
![test](https://github.com/user-attachments/assets/efaeb35b-aea3-4157-a82b-015736d6117e)

```
java.lang.RuntimeException: Canvas: trying to draw too large(308544000bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
at androidx.compose.ui.graphics.AndroidCanvas.drawImageRect-HPBpro0(AndroidCanvas.android.kt:275)
at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawImage-AZ2fEMs(CanvasDrawScope.kt:256)
at androidx.compose.ui.node.LayoutNodeDrawScope.drawImage-AZ2fEMs(Unknown Source:24)
at androidx.compose.ui.graphics.drawscope.DrawScope.drawImage-AZ2fEMs$default(DrawScope.kt:551)
at androidx.compose.ui.graphics.painter.BitmapPainter.onDraw(BitmapPainter.kt:93)
at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
at coil3.compose.AsyncImagePainter.onDraw(AsyncImagePainter.kt:211)
at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
at com.github.panpf.zoomimage.compose.coil.internal.ContentPainterModifier.draw(ContentPainterModifier.kt:205)
at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:349)
at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:364)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:66)
at com.github.panpf.zoomimage.compose.subsampling.SubsamplingDrawTilesNode.draw(subsampling.common.kt:104)
at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:364)
at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:383)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:382)
at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:382)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:380)
at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:335)
at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1236)
at android.view.View.draw(View.java:23892)
at android.view.View.updateDisplayListIfDirty(View.java:22756)
at android.view.View.draw(View.java:23620)
at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
at android.view.View.updateDisplayListIfDirty(View.java:22747)
at android.view.View.draw(View.java:23620)
at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
at android.view.View.updateDisplayListIfDirty(View.java:22747)
at android.view.View.draw(View.java:23620)
at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317) (Ask Gemini)
at android.view.View.updateDisplayListIfDirty(View.java:22747)
at android.view.View.draw(View.java:23620)
at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
at android.view.View.draw(View.java:23892)
at com.android.internal.policy.DecorView.draw(DecorView.java:809)
at android.view.View.updateDisplayListIfDirty(View.java:22756)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Affected platforms**

- Android (Compose Multiplatform)

**Affected components**

- CoilAsyncZoomImage

**Versions**

- zoomimage version*: 1.1.0-alpha05
- Kotlin version*: 1.9.23
- Compose version(s)* (Jetpack/Multiplatform): compose bom 2024.05.00

**Running Devices**

Please accurately describe the device Model, OS version, and CPU Architecture

- android emulator OS 14

**Sample code**

```
val imageRequest = ImageRequest.Builder(koinInject<PlatformContext>())
        .data("url/path to large image")
        .size(coil3.size.Size.ORIGINAL)
        .build()
    val zoomableState: CoilZoomState = rememberCoilZoomState()
    val imageLoader = koinInject<ImageLoader>()
    CoilZoomAsyncImage(
        modifier = modifier,
        model = imageRequest,
        imageLoader = imageLoader,
        zoomState = zoomableState,
        contentDescription = "",
    )
```

**Comment by panpf** [comment]
Don't use CoilZoomAsyncImage first. Try using coil's AsyncImage. You will get the same error.

**Comment by szczepanski-k** [comment]
@panpf what do you mean? AsyncImage is expected to fail as it doesn't contain subsampling. While for CoilZoomAsyncImage subsampling should work out of the box in accordance to this doc https://github.com/panpf/zoomimage/blob/main/docs/wiki/subsampling.md right?

**Comment by szczepanski-k** [comment]
How to make the subsampling work then?

**Comment by szczepanski-k** [comment]
For example - this subsampling lib for standard view (non compose) works fine on the same image https://github.com/davemorrissey/subsampling-scale-image-view

**Comment by panpf** [comment]
Remove it `size(coil3.size.Size.ORIGINAL)`

**Comment by szczepanski-k** [comment]
But then it will load low-res image, so what's the point of subsampling? Are you saying that subsampling in fact doesn't work for this lib?

**Comment by panpf** [comment]
If you always load the image at its original resolution, why do you need to subsample?

**Comment by szczepanski-k** [comment]
Ok, then how to achieve subsampling? I removed the line `size(coil3.size.Size.ORIGINAL)`. It doesn't crash but the image is in low resolution and after zooming tiles with better resolution are not being loaded.

Do you have any suggestion how to make it work with CoilZoomAsyncImage? Or any other way in compose multiplatform?

**Comment by panpf** [comment]
What is data in the line `data("url/path to large image")`?

**Comment by szczepanski-k** [comment]
In my case it's a custom model containing URL but I use coil's ImageLoader.diskCache so it can be also a file from the cache.

**Comment by panpf** [comment]
对于自定义的模型，你需要参考 CoilModelToImageSourceImpl 去实现你的 CoilModelToImageSource，然后在创建 CoilZoomState 时使用你的 CoilModelToImageSource，如下：
```kotlin
class MyCoilModelToImageSource : CoilModelToImageSource {
    ...
}
val modelToImageSources = remember { listOf(MyCoilModelToImageSource()).toImmutableList() }
val coilZoomState = rememberCoilZoomState(modelToImageSources)
...
```

**Comment by szczepanski-k** [comment]
Yes it works now after implementing CoilModelToImageSource and ImageSource.Factory. Thank you!
